### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yusuke-nm** [you1107exp/furima_28372#9]
# フリマアプリのURL
https://furima-28372.herokuapp.com/
# Basic認証のID、パスワード
you1107、0283720
# 出品者用のメールアドレス、パスワード
user1@sample.com、user01
# 購入者用のメールアドレス、パスワード
user2@sample.com、user02
# 購入用カードの番号・期限・セキュリティコード
4242424242424242、12 20、123

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○出品商品を【編集・削除】しようとするとエラーが出てしまう為、正常に編集や削除ができるようにしましょう。**
<img width="726" alt="スクリーンショット 2020-08-31 14 20 46" src="https://user-images.githubusercontent.com/65144927/91685404-329c9b00-eb95-11ea-927b-20900df479fb.png">



**○一度購入した商品が再度購入できてしまうので、一度売り切れた商品は購入できないようにしましょう。**


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yusuke-nm** [comment]
上記指摘箇所、修正させていただきました。
削除機能に関してですが、購入されていない出品商品が削除できれば要件達成になるという認識でおります。
理由として、購入済み商品を削除しようとする場合、購入テーブル(purchasesテーブル)に保存された商品も削除されないと辻褄が合わなくなってしまう為だと考えられます。
必須機能の実装が終わっているメンバーにも確認しましたが、メンバーも購入されていない出品商品が削除されるように開発できればLGTMという認識でした。
ご確認よろしくお願いいたします。

![](https://i.gyazo.com/78f21c9cfc01511b0886351e83be4b96.png)

![](https://i.gyazo.com/dceff28623f33d866342b547f9d40ceb.png)

![](https://i.gyazo.com/673760b7eed1c029c7409149e0fc614e.png)

**Comment by mutorisa** [comment]
野町さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、問題なく売り切れていない商品の削除及び編集ができました。また、一度売り切れたものが再度購入できなくなっていることも確認できました✨
他の項目についても問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
